 con.close()
        except Exception as e:
            showerror('Error', f"Error due to: {e}", parent=root)